config:
  credentials: []
  project_repos:
    github.com/EGI-Federation/cloud-info-provider:
      branch: master
      repo: https://github.com/EGI-Federation/cloud-info-provider
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EGI-Federation/cloud-info-provider git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-olive-uakari.sh
        container: qc.acc_gummy-flax-centipede
  QC.Doc:
    repos:
      github.com/EGI-Federation/cloud-info-provider find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-cerulean-ant.sh
        container: qc.doc_beady-wheat-impala
      github.com/EGI-Federation/cloud-info-provider git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-viridian-booby.sh
        container: qc.doc_bumpy-harlequin-oriole
      github.com/EGI-Federation/cloud-info-provider markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-khaki-opossum.sh
        container: qc.doc_smelly-chestnut-gorilla
  QC.Lic:
    repos:
      github.com/EGI-Federation/cloud-info-provider licensee:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-corn-dachshund.sh
        container: qc.lic_squirrely-alizarin-blue
  QC.Sec:
    repos:
      github.com/EGI-Federation/cloud-info-provider bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-mauve-manatee.sh
        container: qc.sec_hazy-flax-newfoundland
  QC.Sty:
    repos:
      github.com/EGI-Federation/cloud-info-provider flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-ruby-tzu.sh
        container: qc.sty_surly-corn-jellyfish
      github.com/EGI-Federation/cloud-info-provider jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-gamboge-squirt.sh
        container: qc.sty_tasty-heliotrope-goose
  QC.Ver:
    repos:
      github.com/EGI-Federation/cloud-info-provider get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-lavender-bloodhound.sh
        container: qc.ver_flimsy-silver-ray
timeout: 1800
