config:
  credentials: []
  project_repos:
    github.com/EGI-Federation/cloud-info-provider:
      branch: master
      repo: https://github.com/EGI-Federation/cloud-info-provider
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EGI-Federation/cloud-info-provider git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cobalt-otter.sh
        container: qc.acc_frumpy-xanthic-dogfish
  QC.Doc:
    repos:
      github.com/EGI-Federation/cloud-info-provider find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-linen-lizard.sh
        container: qc.doc_squirrely-wheat-sheepdog
      github.com/EGI-Federation/cloud-info-provider git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-salmon-vulture.sh
        container: qc.doc_snippy-firebrick-terrier
      github.com/EGI-Federation/cloud-info-provider markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-brown-fossa.sh
        container: qc.doc_flabby-sepia-lynx
  QC.Lic:
    repos:
      github.com/EGI-Federation/cloud-info-provider licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-goldenrod-javanese.sh
        container: qc.lic_homey-gamboge-akita
  QC.Sec:
    repos:
      github.com/EGI-Federation/cloud-info-provider bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-mauve-terrier.sh
        container: qc.sec_woozy-taupe-rhinoceros
  QC.Sty:
    repos:
      github.com/EGI-Federation/cloud-info-provider flake8:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-tan-otter.sh
        container: qc.sty_sloppy-black-insect
      github.com/EGI-Federation/cloud-info-provider jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-linen-elephant.sh
        container: qc.sty_homey-harlequin-mastiff
  QC.Ver:
    repos:
      github.com/EGI-Federation/cloud-info-provider get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-tan-armadillo.sh
        container: qc.ver_lousy-teal-dane
timeout: 1800
